export const SPACING = {
  CONTAINER_TOP: 64,
  CONTAINER_HORIZONTAL: 24,
  IN_SESSION_TOP: 24,
  IN_SESSION_HORIZONTAL: 12,
  CARD_RADIUS: 28,
  CARD_PADDING: 24,
  CARD_PADDING_TOP_LARGE: 48,
  SECTION_GAP: 16,
  LARGE_ICON: 64,
  CONTENT_GAP: 20,
  FIELD_RADIUS: 14,
  FIELD_PADDING: 14,
  BUTTON_RADIUS: 16,
  BUTTON_PADDING: 16,
  ACTION_RADIUS: 24
} as const;

