services:
  backend:
    build:
      context: ../backend
      dockerfile: ../infra/docker/backend.Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 50001 --reload
    environment:
      CHAT_CORS_ALLOWED_ORIGINS: http://localhost:3000
      CHAT_CORS_ALLOW_CREDENTIALS: "false"
      CHAT_DATABASE_URL: sqlite:///./data/chat_orbit.db
    ports:
      - "50001:50001"
    restart: unless-stopped
    volumes:
      - ../backend:/app
      - backend_data:/app/data

  frontend:
    build:
      context: ../frontend
      dockerfile: ../infra/docker/frontend.Dockerfile
    command: pnpm dev --port 3000 --hostname 0.0.0.0
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:50001
      NEXT_PUBLIC_WS_BASE_URL: ws://localhost:50001
      NEXT_PUBLIC_WEBRTC_DEFAULT_STUN_URLS: stun:stun.l.google.com:19302
      NEXT_PUBLIC_WEBRTC_DEFAULT_TURN_URLS: turn:turn.chatorbit.com:443,turn:turn.chatorbit.com:443?transport=tcp
      NEXT_PUBLIC_WEBRTC_TURN_USERNAME: pakalolo
      NEXT_PUBLIC_WEBRTC_TURN_CREDENTIAL: 275ea323d4eac7f635ef5cd3518f32af957beaeb6e6579fad5e1009903b7d5e4
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ../frontend:/app

volumes:
  backend_data: {}
