services:
  backend:
    build:
      context: ../backend
      dockerfile: ../infra/docker/backend.Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 50001
    env_file:
      - ./.env.production
    ports:
      - "127.0.0.1:50001:50001"
    restart: unless-stopped
    volumes:
      - backend_data:/app/data

  frontend:
    build:
      context: ../frontend
      dockerfile: ../infra/docker/frontend.Dockerfile
    command: >-
      sh -c "pnpm build && HOSTNAME=0.0.0.0 PORT=3000 pnpm start"
    depends_on:
      - backend
    env_file:
      - ./.env.production
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped

volumes:
  backend_data: {}
